version: 2

jobs:
  
  test1:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/included:4.3.0'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress tests 1
          command: $(npm bin)/cypress run --record --key 7df33d1e-0d41-4a6e-87dc-22586aaffb96 --spec cypress/integration/Tests/Login_demoTest_Second.spec.js

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test2:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/included:4.3.0'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress tests 2
          command: $(npm bin)/cypress run --record --key 7df33d1e-0d41-4a6e-87dc-22586aaffb96 --spec cypress/integration/Tests/Login_demoTest.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  

workflows:
  version: 2
  build_and_test:
    jobs:
      
      - test1:
        
      - test2:
     
     